nelmio_api_doc:
  documentation:
    info:
      title: My App
      description: This is an awesome app!
      version: 1.0.0
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc)(?!.json$) # Accepts routes under /api except /api/doc


#nelmio_api_doc:
#  documentation:
#    host: api.example.com
#    schemes: [http, https]
#    info:
#      title: My App
#      description: This is an awesome app!
#      version: 1.0.0
#    securityDefinitions:
#      Bearer:
#        type: apiKey
#        description: 'Value: Bearer {jwt}'
#        name: Authorization
#        in: header
#    security:
#      - Bearer: []
